### ISSUE TITLE
One can copy skill to any event

### ISSUE THREAD

**Issue by PierreAnctil** [worldskills/worldskills-events#82]
On the skill list of an event, one can copy the skills of the current to events they do not have access to.

**Example:**
Simon Woirgard in staging has only access to *National Skills Competition, WorldSkills France.* but the copy button display many possible events
![image](https://user-images.githubusercontent.com/6544411/35611885-dd61abe6-0666-11e8-9fa2-8892e0b3d193.png)

I didn't try to actually do the copy though, that might be blocked by the API.

**Comment by fabian** [comment]
Thanks for the report! Yes, we check the permissions in the API, so it wouldn't work.

But I agree it would be better to only display the events the user has access to.
